name: pr-validation
concurrency: ${{ github.event.number }}

on: pull_request

permissions:
  id-token: write
  contents: read

env:
  resourceGroupName: pr_${{ github.event.number }}
  resourceGroupLocation: westus3

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        run: |  
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}  
      - uses: Azure/cli@v1
        name: Create resource group
        with:
          inlineScript: |
            az group create \
              --name ${{ env.resourceGroupName }} \
              --location ${{ env.resourceGroupLocation }}
      - uses: azure/arm-deploy@v1
        id: deploy
        name: Deploy Bicep file
        with:
          failOnStdErr: false
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./deploy/main.bicep
          parameters: >
            environmentType=Test
      - name: Show website hostname
        run: |
          echo "Access the website at this address: https://${{ steps.deploy.outputs.appServiceAppHostName }}"